
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symc {
  /* terminals */
  public static final int RVIS = 28;
  public static final int SPYC = 19;
  public static final int SMAS = 5;
  public static final int RMIN = 37;
  public static final int SFPA = 20;
  public static final int PID = 2;
  public static final int SDPU = 9;
  public static final int RFEL = 41;
  public static final int SPUN = 10;
  public static final int PNUM = 8;
  public static final int SFCO = 17;
  public static final int RCUR = 23;
  public static final int RCOL = 39;
  public static final int RVER = 16;
  public static final int RNEG = 33;
  public static final int RBOR = 27;
  public static final int RDER = 30;
  public static final int RLET = 24;
  public static final int SDIV = 13;
  public static final int RJUS = 40;
  public static final int EOF = 0;
  public static final int RTEX = 22;
  public static final int PCOM = 7;
  public static final int RAUR = 42;
  public static final int error = 1;
  public static final int SIGU = 11;
  public static final int RALI = 34;
  public static final int RCEN = 32;
  public static final int RMAY = 36;
  public static final int SMUL = 12;
  public static final int CUR = 31;
  public static final int RHOR = 15;
  public static final int ROPA = 26;
  public static final int SCOM = 3;
  public static final int RGRU = 25;
  public static final int SMEN = 6;
  public static final int SIPA = 18;
  public static final int RCAP = 38;
  public static final int RTAM = 4;
  public static final int RFOR = 29;
  public static final int SICO = 14;
  public static final int RID = 21;
  public static final int RIZQ = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PID",
  "SCOM",
  "RTAM",
  "SMAS",
  "SMEN",
  "PCOM",
  "PNUM",
  "SDPU",
  "SPUN",
  "SIGU",
  "SMUL",
  "SDIV",
  "SICO",
  "RHOR",
  "RVER",
  "SFCO",
  "SIPA",
  "SPYC",
  "SFPA",
  "RID",
  "RTEX",
  "RCUR",
  "RLET",
  "RGRU",
  "ROPA",
  "RBOR",
  "RVIS",
  "RFOR",
  "RDER",
  "CUR",
  "RCEN",
  "RNEG",
  "RALI",
  "RIZQ",
  "RMAY",
  "RMIN",
  "RCAP",
  "RCOL",
  "RJUS",
  "RFEL",
  "RAUR"
  };
}

