
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class symj {
  /* terminals */
  public static final int SMAY = 11;
  public static final int SILL = 20;
  public static final int SPYC = 17;
  public static final int SMAS = 5;
  public static final int ROBT = 31;
  public static final int ROBS = 39;
  public static final int SPOT = 9;
  public static final int RDIM = 27;
  public static final int SFPA = 14;
  public static final int PID = 43;
  public static final int RMIE = 38;
  public static final int RIMP = 36;
  public static final int SPUN = 4;
  public static final int PNUM = 12;
  public static final int SDPN = 18;
  public static final int RCON = 29;
  public static final int RDOC = 2;
  public static final int RPAR = 26;
  public static final int SFLL = 21;
  public static final int SNOT = 19;
  public static final int SAND = 23;
  public static final int RDET = 33;
  public static final int RMEN = 34;
  public static final int RSIN = 25;
  public static final int SDIV = 8;
  public static final int PCOM = 42;
  public static final int EOF = 0;
  public static final int PFEC = 44;
  public static final int RDEF = 32;
  public static final int error = 1;
  public static final int SIGU = 15;
  public static final int SMUL = 7;
  public static final int RSET = 41;
  public static final int RSI = 24;
  public static final int SMOD = 10;
  public static final int SCOM = 16;
  public static final int RSEL = 40;
  public static final int SOR = 22;
  public static final int RRET = 35;
  public static final int SMEN = 6;
  public static final int RCAS = 28;
  public static final int SIPA = 13;
  public static final int PHOR = 3;
  public static final int RATE = 37;
  public static final int RFUN = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RDOC",
  "PHOR",
  "SPUN",
  "SMAS",
  "SMEN",
  "SMUL",
  "SDIV",
  "SPOT",
  "SMOD",
  "SMAY",
  "PNUM",
  "SIPA",
  "SFPA",
  "SIGU",
  "SCOM",
  "SPYC",
  "SDPN",
  "SNOT",
  "SILL",
  "SFLL",
  "SOR",
  "SAND",
  "RSI",
  "RSIN",
  "RPAR",
  "RDIM",
  "RCAS",
  "RCON",
  "RFUN",
  "ROBT",
  "RDEF",
  "RDET",
  "RMEN",
  "RRET",
  "RIMP",
  "RATE",
  "RMIE",
  "ROBS",
  "RSEL",
  "RSET",
  "PCOM",
  "PID",
  "PFEC"
  };
}

